import pandas as pd
read = pd.read_csv("D:/MINTIC/Programación/Curso1/Semana_6/Babies.csv", sep=";")
df = pd.DataFrame(read)
print(type(df))
print(df.shape)
print(df.head(7))
print(df['Peso_nacer'])
print(df.Talla_hoy.unique())
print(df.keys())
print(df.info())
print(df.dtypes.value_counts())
print(df.describe())
print(df.loc[6])
print(df.iloc[2,2])
print(df.isnull().any())